### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Sebioff** [dmc31a42/ParkitectKoreanPatcher#3]
I only found this project today because I saw a Korean streamer and wondered how they got the font into the game :D
This is incredibly impressive! Thanks for your support and for maintaining your translation, and I hope the quality of our translation will be as good as yours.

**Comment by telk5093** [comment]
@Sebioff I appreciate your official korean translations. I had also streamed via twitch to check my translation is fine.

But your official korean translation is VERY BAD now.
Little parts are better than mine, but totally it is BAD for native korean tycoon game users.

 * Not all translated (I think the translator uses 1.1 strings)

 * Wrong word select / Mistranslations
    * Ride: 라이드(official) => 놀이기구
    * Old Bill (in Orchard Acres's desc.): 올드 빌(official) => 빌 어르신
    * Swinging ship: 흔들리는 배(official) => 바이킹
    * Info kiosk: 정보 키오스크(official) => (안내소)
    * Duel: 듀엘링(official, and not familiar word to korean) => 듀얼(familar one) or 쌍둥이(means "twins")

 * Not displayed fonts in the pull down menus

  * 이상 => 초과 or 넘게
  Your campaign objectives describes such as "Have a happiness rating of _at least_ 70%", but these rating objectives are completed when it is _more than (but not equal to)_ 70%.

 * Typos
   * 적합합(official) => 적합함(correct)

 * Security: 보안(official) => 경비원

 * Ununified words
    * 직원 경로(used staffs window) vs 사원 경로

 * Mismatch of the subject and the predicate for korean (주어와 서술어의 불일치)
   * Zalgonia's description: 큰 산악 지대가 있는 저택은 ~ 토지를 구입할 수 있습니다.

 * Date order is incorrect
 Korean uses ``{month}/{day}`` order, not ``{day}/{month}``. But all dates in your official korean translation uses ``{day}, {month}``. And I know that it could be able to change their order in .po file, but your translator DID NOT.
    * Additionally, the date in the finance window is not translatable. Korean should reverse the order between month and date.
    ![image](https://user-images.githubusercontent.com/10726524/50424880-50d5d200-08af-11e9-8bbf-f89761b261b8.png)


 * Not all letters are displayed
 My(exactly 'our') patcher contains about 2300 korean letters in font, but 730 of yours.
 It leads to unable to write almost korean letters that is highly used.

 * etc...... Its too many so I cannot describe all of them here.


**And my personal opinions:**
 * Some region names in the campaign are completely translated but others are just reading english into korean. I think it must be unified.

 * "Path" is translated as "경로", but I think it is better than use "길" or "보도"

 * 일군의 파괴행위자: Not familiar words to normal korean user.

I will write all details later, but as you can see above, your official korean translation is entirely bad now.
I have felt that the translator saw only texts you gave without playing the game.

What do you think that your professional translator's output is worse than amateurs, with almost same preparing time(2~3 weeks), and different pay? (they are paid, and I'm not.)

**Comment by Sebioff** [comment]
Thanks. It is very hard for us to figure out if the quality of a translation is good, so this is great to know. I think you are right, they didn't play the game. We will have to talk to them.

**Comment by telk5093** [comment]
@Sebioff Please let them know my email address(telk5093@gmail.com) when you talk to them.
They SHOULD contact to translate correctly real Parkitect game player, if they won't play the game.
(Or, you can hire me ;D)

+ And the finance window part is untranslatable because of technical issue (I think) like "~ are drowned" as I mentioned at the Steam forum before.

**Comment by studiocavy** [comment]
@Sebioff Here's an another Korean big fan of this game. Unfortunately, the official translation seems to be neither done by native speakers (maybe Korean-Chinese, I think.) nor by anyone who has ever played games. Even if you are planning to improve current translation, why don't you release original strings to Korean fans and get feedback?

Most fans of yours have experience playing the Roller Coaster Tycoon series and tend to be familiar with the vocabulary used in the Korean version of that game. For instance, "janitor" translated to "관리인" in Parkitect - It's not a incorrect translation but this word is generally accepted as a "general manager" rather than a "cleaner" in Korean. The point is, the game has to be translated into the nuance that the players want.
